version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: my_backend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
