# Imagem base
FROM node:18

# Cria diretório da aplicação
WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o restante do código
COPY . .

# Expõe a porta do servidor
EXPOSE 3000

# Comando para iniciar a aplicaçã
CMD ["npm", "run", "dev"]
